# Playbook for installing my shell dependencies.
#
# Usage: ansible-playbook -i "localhost," -c local -K playbook.yml [--skip-tags extra]
#
---

- hosts: all
  vars:
    rust_user: "{{ ansible_user_id }}"

  tasks:
    - name: On Arch Linux
      when: ansible_os_family == 'Arch Linux'
      become: true
      block:
        - name: Update cache
          pacman:
            update_cache: true

        - name: zsh | Install
          pacman:
            name:
              - zsh
              - fasd
              - git

        - name: tmux | Install
          pacman:
            name:
              - tmux
              - tmate-git
              - tmuxinator
            state: present

        - name: extras | Install
          pacman:
            name:
              - fd
              - glances
              - mc
              - ripgrep
              - the_silver_searcher
              - tree
            state: present

    - name: On Debian/Ubuntu
      when: ansible_os_family == 'Debian'
      become: true
      block:
        - name: fasd | Add repository
          apt_repository:
            repo: ppa:aacebedo/fasd
          when: ansible_distribution_release != "bionic"

        - name: Update cache
          apt:
            update_cache: true

        - name: zsh | Install
          apt:
            name:
              - zsh
              - fasd
              - git
            state: present

        - name: tmux | Install
          apt:
            name:
              - tmux
              - tmate
              - tmuxinator
            state: present

        - name: extras | Install
          apt:
            name:
              - glances
              - mc
              - silversearcher-ag
              - tree
            state: present

    - name: zsh | Make default for user
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
        update_password: on_create

    - name: On Debian/Ubuntu
      when: ansible_os_family == 'Debian'
      block:
        - name: rust | Get rustup binary path
          set_fact:
            cargo_bin_dir: "{{ ansible_user_dir }}/.cargo/bin"
            rustup_binary: "{{ ansible_user_dir }}/.cargo/bin/rustup"
            cargo_binary: "{{ ansible_user_dir }}/.cargo/bin/cargo"

        - name: rust | Install rustup
          shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
          args:
            creates: "{{ rustup_binary }}"
            warn: false

        - name: ripgrep | Install
          command: "{{ cargo_binary }} install ripgrep"
          args:
            creates: "{{ cargo_bin_dir }}/rg"

        - name: fd-find | Install
          command: "{{ cargo_binary }} install fd-find"
          args:
            creates: "{{ cargo_bin_dir }}/fd"
